// Bibliothèque officielle de phrases Normasense
const normasenseQuotes = [
  "Le passé enseigne, mais ne décide plus.",
  "Le présent est le seul moment où l’on peut agir.",
  "Le futur se prépare, il ne se devine pas.",
  "Ce que tu fais aujourd’hui construit ce que tu vivras demain.",
  "Le temps ne guérit pas tout, mais il révèle beaucoup.",
  "Chaque jour est une occasion de mieux comprendre.",
  "Rien ne change si rien n’est compris.",
  "Avancer ne signifie pas oublier.",
  "Le futur n’a pas besoin d’être parfait, seulement conscient.",
  "Le temps perdu est souvent celui mal compris.",

  "Penser avant d’agir évite souvent de regretter.",
  "Comprendre vaut mieux que réagir.",
  "La lucidité est une forme de liberté.",
  "L’intelligence commence par l’observation.",
  "Réfléchir n’est pas hésiter, c’est se préparer.",
  "Une décision éclairée est déjà à moitié réussie.",
  "Le calme permet de voir ce que la précipitation cache.",
  "Ce que tu comprends te contrôle moins.",
  "La conscience précède toujours le changement.",
  "Penser juste est plus important que penser vite.",

  "Chaque choix porte une conséquence, visible ou non.",
  "Ne pas choisir est aussi un choix.",
  "Assumer est plus léger que fuir.",
  "Les décisions difficiles forgent la stabilité.",
  "La responsabilité donne du poids aux actions.",
  "Ce que tu refuses de décider décidera pour toi.",
  "Un bon choix n’est pas toujours confortable.",
  "La liberté demande de la responsabilité.",
  "Choisir en conscience évite bien des retours en arrière.",
  "La maturité se voit dans les décisions silencieuses.",

  "La constance dépasse le talent.",
  "Ce qui est répété devient une habitude.",
  "La discipline protège quand la motivation disparaît.",
  "Construire prend du temps, détruire prend un instant.",
  "Les petites actions régulières bâtissent les grands résultats.",
  "La patience est une stratégie.",
  "Ce que tu négliges aujourd’hui te rattrape demain.",
  "La rigueur simplifie l’avenir.",
  "Rien de solide ne se construit dans la précipitation.",
  "La persévérance est une forme d’intelligence.",

  "Se connaître évite de se perdre.",
  "La valeur ne dépend pas du regard des autres.",
  "Être soi demande parfois du courage.",
  "L’identité se construit, elle ne se reçoit pas.",
  "Se respecter change la manière dont on est traité.",
  "La comparaison brouille la perception de soi.",
  "Grandir, c’est parfois se détacher.",
  "La clarté intérieure attire la stabilité extérieure.",
  "S’accepter est un travail, pas un hasard.",
  "La confiance se bâtit sur la cohérence.",

  "Tout n’est pas urgent.",
  "L’équilibre vient de la compréhension des limites.",
  "Trop ou trop peu mènent souvent au même désordre.",
  "La réalité se comprend mieux quand on l’affronte calmement.",
  "Ignorer un problème ne le fait pas disparaître.",
  "La simplicité est souvent une solution mûrie.",
  "Tout n’a pas besoin d’une réaction immédiate.",
  "Le recul permet la justesse.",
  "Comprendre le contexte change le jugement.",
  "La mesure protège des excès.",

  "Apprendre ne s’arrête jamais.",
  "Chaque erreur contient une information.",
  "L’expérience affine la perception.",
  "Celui qui apprend progresse, même lentement.",
  "Le savoir protège des répétitions inutiles.",
  "Grandir, c’est corriger sans se condamner.",
  "L’évolution commence par l’acceptation.",
  "Comprendre ses limites est une force.",
  "La connaissance réduit les regrets.",
  "Apprendre à temps évite de réparer plus tard.",

  "Tout le monde agit selon ce qu’il comprend.",
  "Écouter éclaire plus que parler.",
  "La compréhension réduit les conflits.",
  "Observer avant de juger change tout.",
  "Le respect commence par la lucidité.",
  "Les intentions comptent, mais les actes parlent.",
  "Comprendre les autres commence par se comprendre.",
  "Le silence peut être une réponse réfléchie.",
  "La cohérence inspire plus que les discours.",
  "La clarté évite les malentendus.",

  "Avancer sans sens fatigue.",
  "Donner un sens guide les efforts.",
  "Le pourquoi soutient le comment.",
  "La direction importe plus que la vitesse.",
  "Savoir où l’on va réduit l’égarement.",
  "Le sens donne de la stabilité.",
  "Une vie réfléchie est plus cohérente.",
  "Le but éclaire le chemin.",
  "Comprendre sa direction apaise.",
  "Le sens transforme les difficultés.",

  "Tout ne dépend pas de toi, mais quelque chose oui.",
  "Le contrôle excessif fatigue l’esprit.",
  "Accepter n’est pas abandonner.",
  "La sagesse consiste à discerner.",
  "La paix intérieure naît de la clarté.",
  "Ce qui est compris est moins lourd.",
  "La réflexion précède la stabilité.",
  "Le calme est une force discrète.",
  "Comprendre donne du pouvoir sans violence.",
  "Une vie consciente est rarement regrettée."
];

// Affichage aléatoire à chaque visite
document.addEventListener("DOMContentLoaded", () => {
  const quoteElement = document.getElementById("daily-quote");
  if (quoteElement) {
    const randomIndex = Math.floor(Math.random() * normasenseQuotes.length);
    quoteElement.textContent = "“" + normasenseQuotes[randomIndex] + "”";
  }
});
